config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  # get "/users", to: "users#index" 
  # get "/users/:id", to: "users#show"
  # get "/users/:user_id/posts", to: "posts#index"
  # get "/users/:user_id/posts/:id", to: "posts#show"
  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :likes, only: [:create]
      resources :comments, only: [:new, :create]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users ,only: [:index] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create] 
      end
    end
  end
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  # Association
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'

  # methods
  def update_comment_count
    post.update(comments_counter: post.comments.count)
    post.comments.count
  end
end

app/models/like.rb
class Like < ApplicationRecord
  # Association
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'

  # methods
  def update_like_count
    post.update(likes_counter: post.likes.count)
    post.likes.count
  end
end

app/models/post.rb
class Post < ApplicationRecord
  # Association
  belongs_to :user, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, class_name: 'Comment', dependent: :destroy
  has_many :likes, class_name: 'Like', dependent: :destroy

  # methods
  def update_post_count
    user.update(post_counter: user.posts.count)
  end

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  # validation
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  # Association
  has_many :posts, class_name: 'Post', foreign_key: 'author_id', dependent: :destroy
  has_many :comments, class_name: 'Comment', foreign_key: 'user_id', dependent: :destroy
  has_many :likes, class_name: 'Like', foreign_key: 'user_id', dependent: :destroy

  # methods
  def recent_post
    posts.order(created_at: :desc).limit(3)
  end
  # validation
  validates :name, presence: true
  validates :post_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
    @comments = @post.comments.includes(:user)
    render json: { success: true, data: @comments }, include: %w[user]
  end

  def create
    @comment = current_user.comments.build(comments_params)
    if @comment.save
      render json: { success: true, data: @comment }, status: :created
    else
      render json: { error: @comment.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def comments_params
    params.require(:comment).permit(:text).merge(post_id: params[:post_id])
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:likes, :comments)

    render json: { success: true, data: @posts }, include: %w[user comments]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :bio, :password, :photo) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :surname, :email, :bio, :password, :current_password, :photo)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = current_user.comments.build(comments_params)
    if @comment.save
      flash[:notice] = 'Comment was created seccesufuly'
      redirect_to user_posts_path
    else
      render :new
    end
  end

  def comments_params
    params.require(:comment).permit(:text).merge(post_id: params[:post_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = Like.new(user: current_user, post: @post)

    if @like.save
      flash[:notice] = 'You liked this post!'
      redirect_to user_posts_path
    else
      flash[:alert] = 'Something went wrong!'
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.page(params[:page]).per(3)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(params.require(:post).permit(:title, :text))
    if @post.save
      flash[:notice] = 'Post was created seccesufuly'
      redirect_to user_path(id: current_user)
    else
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comments/new.html.erb
<div class="container mt-5">
<%= form_with(model:[@comment], local: true, url: user_post_comments_path) do |f| %>
   <div class="mb-3">
    <%= f.label :text, class: "text-dark fs-3 fw-bold  form-label", for: "exampleFormControlTextarea1" %><br/>
    <%= f.text_area  :text, class: "px-2 w-100 form-control",   id: "exampleFormControlTextarea1", rows:"3"%>
  </div>
  <p>
    <%= f.submit class: "btn btn-success  px-4" %>
  </p>
<% end %>
  <%= link_to "Go to Posts Page", user_posts_path, class: "btn btn-success ms-3" %>
</div>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
<div class="alert alert-primary alert-dismissible" role="alert">
    <div class="fs-5 fw-bold">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
</div>
  <%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
  <%= render '/layouts/messages'%>
    <%= yield %>
  </body>
</html>

app/views/likes/_new.html.erb
<div>
<%= form_with model: @like, url: user_post_likes_path(post_id: @post.id) do |f|%>
  <%= f.submit "Like", class: "btn btn-success  " %>
   <%= link_to "Go to comment", new_user_post_comment_path(post_id: @post.id), class: "btn btn-success " %>
<% end %>
</div>

app/views/posts/_form.html.erb
<%= form_with(model:[@user, @post], local: true, url: user_posts_path) do |f| %>
 <div class="mb-3">
    <%= f.label :title, class: "text-dark fs-3 fw-bold  form-label",  for: "exampleFormControlInput1"%><br/>
    <%= f.text_field :title, class: "px-3 form-control", id: "exampleFormControlInput1"%>
  </div>
   <div class="mb-3">
    <%= f.label :text, class: "text-dark fs-3 fw-bold  form-label", for: "exampleFormControlTextarea1" %><br/>
    <%= f.text_area  :text, class: "px-2 w-100 form-control",   id: "exampleFormControlTextarea1", rows:"3"%>
  </div>
  <p>
    <%= f.submit class: "btn btn-success  px-4" %>
  </p>
<% end %>

app/views/posts/index.html.erb
<div class="container d-flex flex-column  justify-content-center align-items-center pt-5">
<div class="item  d-flex  justify-content-end align-items-center  ">
<%= button_to(
  "Log Out",
        destroy_user_session_path,
        method: :delete
      ) %>
</div>
 <li class="list-group-item d-flex justify-content-start gap-4 align-items-star mt-5 item">
  <span><img src="https://picsum.photos/id/64/200" class="card-img-top imgs" alt="..."></span>
  <span class="d-flex justify-content-start gap-4 align-items-start">
   name: <%= @user.name %>
  <span class="badge bg-primary rounded-pill"> number of posts: <%= @user.posts.count %> </span>
  </span>
  </li>
  <% @posts.includes(:likes, :comments).each do |post| %>
  <a href="<%= user_post_path(@user, post) %>" class="text-decoration-none">
    <li class="list-group-item d-flex justify-content-between align-items-start mt-5 item">
    <div class="ms-2 me-auto">
      <div class="fw-bold">Post # <%= post.id%></div>
     <p>Title: <%= post.title %></p>
      <p>Body: <%= post.text  %></p>
    </div>
    <div class=" d-flex justify-content-between gap-2 align-items-start">
    <span class="badge bg-primary rounded-pill">Comments: <%= post.comments.count%></span>
    <span class="badge bg-primary rounded-pill">Likes: <%= post.likes.count %></span>
    </div>
  </li>
  </a>
  <ul class="list-group-item item mt-2 ">
   <% post.recent_comments.includes(:user).each do |comment| %>
 <li class="list-group-item">username:  <%= comment.user.name %> comment:  <%= comment.text%> </li> 
  <%end%>
  </ul>
  <%end%>
  <div class='d-flex justify-content-center align-items-center pt-5'>
  <%= link_to "Create new Post", new_user_post_path, class: "btn btn-success ms-3 mb-4" %>
  </div>
  <div class="pagination mb-4">
    <%= paginate @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container mt-5">
<h1 class="fs-1 text-success text-center">Create new Post</h1>
<%= render 'form'%>
<%= link_to "Back Posts listing", user_posts_path, class: "btn btn-success ms-3 mt-5  px-3" %>
</div>

app/views/posts/show.html.erb
<div class="container d-flex flex-column  justify-content-center align-items-center pt-5">
<h1>This Post details for a User</h1>
    <li class="list-group-item d-flex justify-content-between align-items-start mt-5 item">
    <div class="ms-2 me-auto">
      <div class="fw-bold">Post # <%= @post.id%> by <%= User.find(@post.author_id).name %></div>
      <p>Title: <%= @post.title %></p>
      <p>Body: <%= @post.text  %></p>
    </div>
    <div class=" d-flex justify-content-between gap-2 align-items-start">
    <span class="badge bg-primary rounded-pill">Comments: <%= @post.comments.count%></span>
    <span class="badge bg-primary rounded-pill">Likes: <%= @post.likes.count %></span>
    </div>
  </li>
  <ul class="list-group-item item mt-2 ">
   <% @post.comments.includes(:user).each do |comment| %>
 <li class="list-group-item">username:  <%= comment.user.name %> comment:  <%= comment.text%> </li> 
  <%end%>
  </ul>

  <div class='d-flex justify-content-center align-items-center'>
  <%= render 'likes/new', post: @post, like: @like %>
  <%= link_to "Go to Posts Page", user_posts_path, class: "btn btn-success ms-3" %>

  </div>
</div>

app/views/rswag/ui/home/index.html.erb
<!-- HTML for static distribution bundle build -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Blog App API</title>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Source+Code+Pro:300,600|Titillium+Web:400,600,700" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="./swagger-ui.css" >
  <link rel="icon" type="image/png" href="./favicon-32x32.png" sizes="32x32" />
  <link rel="icon" type="image/png" href="./favicon-16x16.png" sizes="16x16" />
  <style>
    html
    {
      box-sizing: border-box;
      overflow: -moz-scrollbars-vertical;
      overflow-y: scroll;
    }
    *,
    *:before,
    *:after
    {
      box-sizing: inherit;
    }

    body {
      margin:0;
      background: #fafafa;
    }
  </style>
</head>

<body>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="position:absolute;width:0;height:0">
  <defs>
    <symbol viewBox="0 0 20 20" id="unlocked">
          <path d="M15.8 8H14V5.6C14 2.703 12.665 1 10 1 7.334 1 6 2.703 6 5.6V6h2v-.801C8 3.754 8.797 3 10 3c1.203 0 2 .754 2 2.199V8H4c-.553 0-1 .646-1 1.199V17c0 .549.428 1.139.951 1.307l1.197.387C5.672 18.861 6.55 19 7.1 19h5.8c.549 0 1.428-.139 1.951-.307l1.196-.387c.524-.167.953-.757.953-1.306V9.199C17 8.646 16.352 8 15.8 8z"></path>
    </symbol>

    <symbol viewBox="0 0 20 20" id="locked">
      <path d="M15.8 8H14V5.6C14 2.703 12.665 1 10 1 7.334 1 6 2.703 6 5.6V8H4c-.553 0-1 .646-1 1.199V17c0 .549.428 1.139.951 1.307l1.197.387C5.672 18.861 6.55 19 7.1 19h5.8c.549 0 1.428-.139 1.951-.307l1.196-.387c.524-.167.953-.757.953-1.306V9.199C17 8.646 16.352 8 15.8 8zM12 8H8V5.199C8 3.754 8.797 3 10 3c1.203 0 2 .754 2 2.199V8z"/>
    </symbol>

    <symbol viewBox="0 0 20 20" id="close">
      <path d="M14.348 14.849c-.469.469-1.229.469-1.697 0L10 11.819l-2.651 3.029c-.469.469-1.229.469-1.697 0-.469-.469-.469-1.229 0-1.697l2.758-3.15-2.759-3.152c-.469-.469-.469-1.228 0-1.697.469-.469 1.228-.469 1.697 0L10 8.183l2.651-3.031c.469-.469 1.228-.469 1.697 0 .469.469.469 1.229 0 1.697l-2.758 3.152 2.758 3.15c.469.469.469 1.229 0 1.698z"/>
    </symbol>

    <symbol viewBox="0 0 20 20" id="large-arrow">
      <path d="M13.25 10L6.109 2.58c-.268-.27-.268-.707 0-.979.268-.27.701-.27.969 0l7.83 7.908c.268.271.268.709 0 .979l-7.83 7.908c-.268.271-.701.27-.969 0-.268-.269-.268-.707 0-.979L13.25 10z"/>
    </symbol>

    <symbol viewBox="0 0 20 20" id="large-arrow-down">
      <path d="M17.418 6.109c.272-.268.709-.268.979 0s.271.701 0 .969l-7.908 7.83c-.27.268-.707.268-.979 0l-7.908-7.83c-.27-.268-.27-.701 0-.969.271-.268.709-.268.979 0L10 13.25l7.418-7.141z"/>
    </symbol>


    <symbol viewBox="0 0 24 24" id="jump-to">
      <path d="M19 7v4H5.83l3.58-3.59L8 6l-6 6 6 6 1.41-1.41L5.83 13H21V7z"/>
    </symbol>

    <symbol viewBox="0 0 24 24" id="expand">
      <path d="M10 18h4v-2h-4v2zM3 6v2h18V6H3zm3 7h12v-2H6v2z"/>
    </symbol>

  </defs>
</svg>

<div id="swagger-ui"></div>
<script>
  (function () {
  window.addEventListener("load", function () {
      setTimeout(function () {

          var logo = document.getElementsByClassName('link');

          logo[0].children[0].alt = "My API";
          logo[0].children[0].src = "/favicon-long.png";
      });
  }); })();
</script>

<!-- Workaround for https://github.com/swagger-api/swagger-editor/issues/1371 -->
<script>
  if (window.navigator.userAgent.indexOf("Edge") > -1) {
    console.log("Removing native Edge fetch in favor of swagger-ui's polyfill")
    window.fetch = undefined;
  }
</script>

<script src="./swagger-ui-bundle.js"> </script>
<script src="./swagger-ui-standalone-preset.js"> </script>
<script>
  window.onload = function () {
    var configObject = JSON.parse('<%= config_object.to_json %>');
    var oauthConfigObject = JSON.parse('<%= oauth_config_object.to_json %>');

    // Apply mandatory parameters
    configObject.dom_id = "#swagger-ui";
    configObject.presets = [SwaggerUIBundle.presets.apis, SwaggerUIStandalonePreset];
    configObject.layout = "StandaloneLayout";

    // If oauth2RedirectUrl isn't specified, use the built-in default
    if (!configObject.hasOwnProperty("oauth2RedirectUrl"))
      configObject.oauth2RedirectUrl = window.location.href.replace("index.html", "oauth2-redirect.html");

    // Build a system
    const ui = SwaggerUIBundle(configObject);

    // Apply OAuth config
    ui.initOAuth(oauthConfigObject);
  }
</script>
</body>

</html>

app/views/users/index.html.erb
<div class="container d-flex flex-column  justify-content-center align-items-center pt-5">
<div class="item  d-flex  justify-content-end align-items-center  ">
<%= button_to(
  "Log Out",
        destroy_user_session_path,
        method: :delete
      ) %>
</div>
<h1>Users</h1>
<ul class="list-group">
<% @users.each do |user| %>
<a href="<%= user_path(user.id)%>" class="text-decoration-none">
  <li class="list-group-item d-flex justify-content-start gap-4 align-items-start item">
  <span><img src="https://picsum.photos/id/64/200" class="card-img-top imgs" alt="..."></span>
  <span class="d-flex justify-content-start gap-4 align-items-start">
   name: <%= user.name %>
  <span class="badge bg-primary rounded-pill"> number of posts: <%= user.posts.count %> </span>
  </span>
  </li>
</a>
<% end %>
</ul>
</div>

app/views/users/show.html.erb
<div class="container d-flex flex-column  justify-content-center align-items-center pt-5">
<h1>This is a User Details</h1>
 <li class="list-group-item d-flex justify-content-start gap-4 align-items-star mt-5 item">
  <span><img src="https://picsum.photos/id/64/200" class="card-img-top imgs" alt="..."></span>
  <span class="d-flex justify-content-start gap-4 align-items-start">
   name: <%= @user.name %>
  <span class="badge bg-primary rounded-pill"> number of posts: <%= @user.posts.count %> </span>
  </span>
  </li>
  <li class="list-group-item mt-5 item"">
    <h5 class="card-title">Bio</h5>
    <p class="card-text"><%= @user.bio  %></p>
  </li>
  <% @user.posts.includes(:likes, :comments).each do |post| %>
  <a href="<%= user_post_path(@user, post) %>" class="text-decoration-none">
    <li class="list-group-item d-flex justify-content-between align-items-start mt-5 item">
    <div class="ms-2 me-auto">
      <div class="fw-bold">Post # <%= post.id%></div>
       <p>Title: <%= post.title %></p>
      <p>Body: <%= post.text  %></p>
    </div>
    <div class=" d-flex justify-content-between gap-2 align-items-start">
    <span class="badge bg-primary rounded-pill">Comments: <%= post.comments.count%></span>
    <span class="badge bg-primary rounded-pill">Likes:<%= post.likes.count %></span>
    </div>
  </li>
  </a>
  <%end%>
  <div class='d-flex justify-content-center align-items-center pt-5'>
  <a href="<%= user_posts_path(user_id: @user.id) %>"  class="btn btn-primary">See All Post</a>
  </div>
</div>Z